name: Terraform CI

on: [push, pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Only check formatting & syntax; no AWS creds needed
      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Init (no backend)
        run: terraform init -backend=false -upgrade

      - name: Terraform Validate
        run: terraform validate -no-color
